services:
  kicad:
    build: .
    image: lab-kicad:latest
    container_name: kicad
    ports:
      - "6901:6901"
    environment:
      - KASMVNC_PASSWORD=test123
      - VNC_RESOLUTION=1360x768
    volumes:
      - kicad-data:/home/labuser/projects
    restart: unless-stopped
    mem_limit: 2g
    shm_size: "2gb"
    storage_opt:
      size: "4G"

volumes:
  kicad-data:
