[supervisord]
nodaemon=true

[program:xvfb]
command=Xvfb :0 -screen 0 1920x1080x24 -nolisten tcp

[program:lxde]
command=startlxde
environment=DISPLAY=":0"

[program:kasmvnc]
command=bash -c "mkdir -p /home/labuser/.vnc && chown labuser:labuser /home/labuser/.vnc && kasmvncserver :1 -geometry 1920x1080 -websocketPort 6901 -websocketInterface 0.0.0.0 -SecurityTypes None -AcceptSetPointer -AcceptKeyEvents -AcceptClipboard -SendPrimary -MaxDisconnectionTime=0"
user=labuser
startsecs=5
stopasgroup=true
killasgroup=true
