[supervisord]
nodaemon=true

[program:xvfb]
command=Xvfb :0 -screen 0 1920x1080x24 -nolisten tcp

[program:lxde]
command=startlxde
environment=DISPLAY=":0"

[program:x11vnc]
command=x11vnc -display :0 -nopw -listen localhost -xkb -forever

[program:novnc]
command=websockify --web=/usr/share/novnc/ 8080 localhost:5900