@startuml "gadim-lab-api-types"

skinparam defaultFontName Monospaced
hide empty members
set separator none

title gadim.lab.api.types

enum Role {
    ADMIN
    STUDENT
    TEACHER
}

enum UserStatus {
    ACTIVE
    INACTIVE
}

enum InstanceStatus {
    CREATING
    RUNNING
    STOPPED
    PAUSED
    ERROR
    TERMINATED
}

interface WorkspaceGroup {
    id() :String
    name() :String
}

interface User {
    userId() :String
    name() :String
    lastName() :String
    studentCode() :String
    password() :String
    status() :UserStatus
    createdAt() :LocalDateTime
}

interface UserRole {
    id() :String
    userId() :String
    role() :Role
}



@enduml