version: "3.8"

services:
  quartus:
    build:
      context: .
      additional_contexts:
        - installer=docker-context/installer
    image: lab-quartus:22.1
    container_name: quartus
    shm_size: 4gb
    environment:
      - KASMVNC_PASSWORD
    ports:
      - "127.0.0.1::6901"
    volumes:
      - quartus-data:/home/labuser/projects

volumes:
  quartus-data:
