#!/bin/bash
export XKL_XMODMAP_DISABLE=1
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

if [ -x /usr/bin/dbus-launch ]; then
    eval "$(dbus-launch --sh-syntax --exit-with-session)"
fi

/usr/bin/startxfce4
